"""Add sort_order to areas

Revision ID: 374030acbd33
Revises: 2d0213647834
Create Date: 2026-05-12 20:15:33.580149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374030acbd33'
down_revision = '2d0213647834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
