"""Add equipment_notes table

Revision ID: 77b248bd052d
Revises: c2f9a8d4e6b1
Create Date: 2026-07-04 07:02:35.067631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b248bd052d'
down_revision = 'c2f9a8d4e6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_notes_equipment_id'), ['equipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Drop the table directly. We deliberately do NOT drop
    # ix_equipment_notes_equipment_id first: MariaDB rejects dropping an index
    # that backs the equipment_id foreign key (error 1553). drop_table removes
    # the table, its indexes, and its FK constraints together.
    op.drop_table('equipment_notes')
